<a href="https://colab.research.google.com/github/ham4286/AI_Programming/blob/main/AI_programming_3(2024).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
text = '''Major League Baseball (MLB) is a professional baseball
organization and the oldest major professional sports league in the
world.'''
result = text_to_word_sequence(text)

print('Original Text:', text)
print('################')
print('Tokenized Text:', result)
print('################')
print(type(result))

Original Text: Major League Baseball (MLB) is a professional baseball 
organization and the oldest major professional sports league in the 
world.
################
Tokenized Text: ['major', 'league', 'baseball', 'mlb', 'is', 'a', 'professional', 'baseball', 'organization', 'and', 'the', 'oldest', 'major', 'professional', 'sports', 'league', 'in', 'the', 'world']
################
<class 'list'>


In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
docs= ['As of 2022, a total of 30 teams play in Major League Baseball—15 teams in the National League (NL) and 15 in the American League (AL)—with 29 in the United States and 1 in Canada.',
       'The NL and AL were formed in 1876 and 1901, respectively. Beginning in 1903, the two leagues signed the National Agreement and cooperated',
'The first few decades of professional baseball were characterized by rivalries between leagues and by players who often jumped from one team or league to another.']
token= Tokenizer()
token.fit_on_texts(docs)
print('word count: {}'.format(token.word_counts))
print(type(token.word_counts))
print('sentence count: {}'.format(token.document_count))
print('How many sentences does each word appear in? {}'.format(token.word_docs))

word count: OrderedDict([('as', 1), ('of', 3), ('2022', 1), ('a', 1), ('total', 1), ('30', 1), ('teams', 2), ('play', 1), ('in', 7), ('major', 1), ('league', 4), ('baseball—15', 1), ('the', 7), ('national', 2), ('nl', 2), ('and', 6), ('15', 1), ('american', 1), ('al', 2), ('—with', 1), ('29', 1), ('united', 1), ('states', 1), ('1', 1), ('canada', 1), ('were', 2), ('formed', 1), ('1876', 1), ('1901', 1), ('respectively', 1), ('beginning', 1), ('1903', 1), ('two', 1), ('leagues', 2), ('signed', 1), ('agreement', 1), ('cooperated', 1), ('first', 1), ('few', 1), ('decades', 1), ('professional', 1), ('baseball', 1), ('characterized', 1), ('by', 2), ('rivalries', 1), ('between', 1), ('players', 1), ('who', 1), ('often', 1), ('jumped', 1), ('from', 1), ('one', 1), ('team', 1), ('or', 1), ('to', 1), ('another', 1)])
<class 'collections.OrderedDict'>
sentence count: 3
How many sentences does each word appear in? defaultdict(<class 'int'>, {'canada': 1, 'as': 1, 'states': 1, '30': 1, 'play': 1, 

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
import tensorflow as tf
text = '최고가 될 때까지 끊임 없이 노력하고 최고가 되어서 떠나라.'
token= Tokenizer()
token.fit_on_texts([text])
 #print('word index: {}'.format(token.word_index))
x = token.texts_to_sequences([text])
y = tf.keras.utils.to_categorical(x, len(token.word_index) + 1)
print(y)

[[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1.]]]


In [ ]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
import numpy as np
reviews = ['너무 재밌네요', '최고에요', '참 잘 만든 영화에요', '추천하고 싶은 영화입니다', '한번 더 보고싶네요',
           '글쎄요', '별로에요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']
classes = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])
token = Tokenizer() # new tokenizer
token.fit_on_texts(reviews)

# text input
x = token.texts_to_sequences(reviews) # text to sequence
padded_x = pad_sequences(x, 4)

# pad sequence
word_size = len(token.word_index) + 1
model = Sequential()
model.add(Embedding(word_size, 8, input_length = 4))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.fit(padded_x, classes, epochs = 20)
print('\n Accuracy: {}'.format(model.evaluate(padded_x, classes)[1]))

Epoch 1/20
1/1 [==============================] - 1s 758ms/step - loss: 0.6969 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 13ms/step - loss: 0.6948 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6928 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6908 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6888 - accuracy: 0.5000
Epoch 6/20
1/1 [==============================] - 0s 10ms/step - loss: 0.6868 - accuracy: 0.5000
Epoch 7/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6847 - accuracy: 0.5000
Epoch 8/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6827 - accuracy: 0.8000
Epoch 9/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6807 - accuracy: 0.8000
Epoch 10/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6787 - accuracy: 0.9000
Epoch 11/20
1/1 [===========

In [ ]:
!rm -r aclImdb
!curl -O https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
!tar -xf aclImdb_v1.tar.gz
!rm -r aclImdb/train/unsup

rm: cannot remove 'aclImdb': No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80.2M  100 80.2M    0     0  9738k      0  0:00:08  0:00:08 --:--:-- 16.6M


In [ ]:
import os, pathlib, shutil, random
from tensorflow import keras
batch_size= 32
base_dir = pathlib.Path("aclImdb")
val_dir =base_dir / "val"
train_dir = base_dir /"train"

for category in ("neg", "pos"):
  os.makedirs(val_dir / category)
  files = os.listdir(train_dir / category)
  random.Random(1337).shuffle(files)
  num_val_samples =int(0.2 *len(files))
  val_files = files[-num_val_samples:]
  for fname in val_files:
    shutil.move(train_dir /category / fname,
    val_dir / category /fname)

train_ds=keras.utils.text_dataset_from_directory(
"aclImdb/train", batch_size=batch_size
)
val_ds =keras.utils.text_dataset_from_directory(
"aclImdb/val", batch_size=batch_size
)
test_ds =keras.utils.text_dataset_from_directory(
"aclImdb/test", batch_size=batch_size
)
text_only_train_ds = train_ds.map(lambda x, y: x)

Found 20000 files belonging to 2 classes.
Found 5000 files belonging to 2 classes.
Found 25000 files belonging to 2 classes.


In [ ]:
from tensorflow.keras import layers

max_length = 600
max_tokens = 20000
text_vectorization = layers.TextVectorization(
max_tokens=max_tokens,
output_mode="int",
output_sequence_length=max_length,
)

text_vectorization.adapt(text_only_train_ds)

int_train_ds = train_ds.map(
 lambda x, y: (text_vectorization(x), y),
 num_parallel_calls=4)
int_val_ds = val_ds.map(
 lambda x, y: (text_vectorization(x), y),
 num_parallel_calls=4)
int_test_ds = test_ds.map(
 lambda x, y: (text_vectorization(x), y),
 num_parallel_calls=4)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class TransformerEncoder(layers.Layer):
  def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
    super().__init__(**kwargs)
    self.embed_dim = embed_dim
    self.dense_dim = dense_dim
    self.num_heads = num_heads
    self.attention = layers.MultiHeadAttention(
    num_heads=num_heads, key_dim=embed_dim)
    self.dense_proj = keras.Sequential(
    [layers.Dense(dense_dim, activation="relu"),
    layers.Dense(embed_dim),]
    )
    self.layernorm_1 =layers.LayerNormalization()
    self.layernorm_2 =layers.LayerNormalization()
  def call(self, inputs, mask=None):
    if mask is not None:
      mask = mask[:, tf.newaxis, :]
    attention_output =self.attention(
      inputs, inputs, attention_mask=mask)
    proj_input =self.layernorm_1(inputs +attention_output)
    proj_output =self.dense_proj(proj_input)
    return self.layernorm_2(proj_input +proj_output)

  def get_config(self):
    config = super().get_config()
    config.update({
    "embed_dim": self.embed_dim,
    "num_heads": self.num_heads,
    "dense_dim": self.dense_dim,
    })
    return config

In [ ]:
vocab_size = 20000
embed_dim = 256
num_heads = 2
dense_dim = 32

inputs = keras.Input(shape=(None,), dtype="int64")
x = layers.Embedding(vocab_size, embed_dim)(inputs)
x = TransformerEncoder(embed_dim, dense_dim, num_heads)(x)
x = layers.GlobalMaxPooling1D()(x)
x = layers.Dropout(0.5)(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model = keras.Model(inputs, outputs)
model.compile(optimizer="rmsprop",
  loss="binary_crossentropy",
  metrics=["accuracy"])
model.summary()
callbacks = [
  keras.callbacks.ModelCheckpoint("transformer_encoder.h5", save_best_only=True)
]

model.fit(int_train_ds, validation_data=int_val_ds, epochs=20, callbacks=callbacks)
model = keras.models.load_model(
  "transformer_encoder.h5",
  custom_objects={"TransformerEncoder": TransformerEncoder}
)
print(f"테스트 정확도: {model.evaluate(int_test_ds)[1]:.3f}")

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import Dense, Flatten, Reshape
from tensorflow.keras.layers import LeakyReLU
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam

img_rows= 28
img_cols = 28
channels = 1
# 입력 이미지 차원
img_shape = (img_rows, img_cols, channels)
# 생성자 입력으로 사용될 잡음 벡터의 크기
z_dim= 100

def build_generator(img_shape, z_dim):
  model = Sequential()
  model.add(Dense(128, input_dim = z_dim))
  model.add(LeakyReLU(alpha=0.01))
  model.add(Dense(28 * 28 * 1, activation = 'tanh'))
  # 생성자의 출력을 이미지 차원으로 변경
  model.add(Reshape(img_shape))
  return model

def build_discriminator(img_shape):
  model = Sequential()
  # 입력 이미지를 일렬로 펼치기
  model.add(Flatten(input_shape = img_shape))
  model.add(Dense(128))
  model.add(LeakyReLU(alpha=0.01))
  model.add(Dense(1, activation='sigmoid'))
  return model

def build_gan(generator, discriminator):
  model = Sequential()
  model.add(generator)
  model.add(discriminator)
  return model

 # 판별자 만들기
discriminator = build_discriminator(img_shape)
discriminator.compile(loss = 'binary_crossentropy', optimizer = Adam(), metrics = ['accuracy'])

 # 생성자 만들기
generator = build_generator(img_shape, z_dim)
discriminator.trainable = False

# GAN 모델 만들기
gan= build_gan(generator, discriminator)
gan.compile(loss = 'binary_crossentropy', optimizer = Adam())

losses = []
accuracies = []
iteration_checkpoints = []

def train(iterations, batch_size, sample_interval):
  # MNIST 데이터셋 로드, [-1, 1]
  (X_train, _), (_, _) = mnist.load_data()
  X_train = X_train / 127.5-1.0
  X_train = np.expand_dims(X_train, axis = 3)

  # 진짜 이미지 레이블: 모두 1
  real = np.ones((batch_size, 1))

  # 가짜 이미지 레이블: 모두 0
  fake = np.zeros((batch_size, 1))

  for iteration in range(iterations):
    # ------------------------
    # 판별자 훈련
    # ------------------------
    # 진짜 이미지에서 랜덤 배치 가져오기
    idx = np.random.randint(0, X_train.shape[0], batch_size)
    imgs = X_train[idx]

    # 가짜 이미지 배치 생성
    z= np.random.normal(0, 1, (batch_size, 100))
    gen_imgs = generator.predict(z)

    # 판별자 훈련
    d_loss_real = discriminator.train_on_batch(imgs, real)
    d_loss_fake= discriminator.train_on_batch(gen_imgs, fake)
    d_loss, accuracy = 0.5 * np.add(d_loss_real, d_loss_fake)

    # --------------------
    # 생성자 훈련
    # --------------------

    # 가짜 이미지 배치 생성
    z = np.random.normal(0, 1, (batch_size, 100))
    gen_imgs = generator.predict(z)

    # 생성자 훈련
    g_loss = gan.train_on_batch(z, real)

    if (iteration + 1) % sample_interval == 0:

      # 훈련이 끝난 후 그래프를 그리기 위해 손실과 정확도 저장
      losses.append((d_loss, g_loss))
      accuracies.append(100.0 * accuracy)
      iteration_checkpoints.append(iteration + 1)

      # 훈련 과정 출력
      print("%d [D 손실: %f, 정확도: %.2f%%] [G 손실: %f]" %
        (iteration + 1, d_loss, 100.0 * accuracy, g_loss))

      # 생성된 이미지 샘플 출력
      sample_images(generator)

def sample_images(generator, image_grid_rows=4, image_grid_columns=4):
  # 랜덤한 잡음 샘플링
  z = np.random.normal(0, 1, (image_grid_rows * image_grid_columns, z_dim))

  # 랜덤한 잡음에서 이미지 생성하기
  gen_imgs = generator.predict(z)

  # 이미지 픽셀 값을 [0, 1] 사이로 스케일 조정
  gen_imgs = 0.5 * gen_imgs + 0.5

  # 이미지 그리드 설정
  fig, axs = plt.subplots(image_grid_rows,
    image_grid_columns,
    figsize=(4, 4),
    sharey=True,
    sharex=True)
  cnt = 0
  for i in range(image_grid_rows):
    for j in range(image_grid_columns):
      # 이미지 그리드 출력
      axs[i, j].imshow(gen_imgs[cnt, :, :, 0], cmap='gray')
      axs[i, j].axis('off')
      cnt += 1

#하이퍼파라미터 설정
iterations = 20000
batch_size = 128
sample_interval = 1000

# 지정된 반복 횟수만큼 GAN 훈련
train(iterations, batch_size, sample_interval)

Streaming output truncated to the last 5000 lines.
4/4 [==============================] - 0s 5ms/step
10000 [D 손실: 0.330634, 정확도: 86.72%] [G 손실: 3.614189]
4/4 [==============================] - 0s 4ms/step
11000 [D 손실: 0.399307, 정확도: 83.98%] [G 손실: 3.686250]
4/4 [==============================] - 0s 4ms/step
12000 [D 손실: 0.416392, 정확도: 79.30%] [G 손실: 2.396514]
1/4 [======>.......................] - ETA: 0s